<?xml version="1.0" encoding="UTF-8"?>
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at https://mozilla.org/MPL/2.0/. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.aldica</groupId>
        <artifactId>aldica-parent</artifactId>
        <version>1.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>aldica-repo-ignite-mem-bm</artifactId>
    <name>Alternative/Alfresco Distributed Cache - Repository Ignite Module - Memory Benchmark</name>

    <properties>
        <project.basePackage>org.aldica.repo.ignite</project.basePackage>
        <moduleId>aldica-mem-bm</moduleId>
        <baseModuleId>aldica</baseModuleId>
        <aldica.version>${project.version}</aldica.version>

        <docker.tests.repository.dependency.artifactIds>de.acosix.alfresco.utility.repo,aldica-repo-ignite,support-tools-repo</docker.tests.repository.dependency.artifactIds>
        <alfresco.repo.docker.java.version>17</alfresco.repo.docker.java.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>de.acosix.alfresco.utility</groupId>
                <artifactId>de.acosix.alfresco.utility.repo</artifactId>
                <version>${acosix.utility.version}</version>
                <type>amp</type>
                <exclusions>
                    <exclusion>
                        <groupId>*</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>aldica-repo-ignite</artifactId>
                <version>${aldica.version}</version>
                <type>amp</type>
                <exclusions>
                    <exclusion>
                        <groupId>*</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>org.orderofthebee.support-tools</groupId>
                <artifactId>support-tools-repo</artifactId>
                <classifier>amp</classifier>
                <version>${ootbee.support-tools.version}</version>
                <type>amp</type>
                <exclusions>
                    <exclusion>
                        <groupId>*</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.alfresco</groupId>
            <artifactId>alfresco-remote-api</artifactId>
            <exclusions>
                <!-- xmlfactory and cxf mess with resteasy / JAX-RS in integration tests -->
                <!-- opencmis exclusion excludes various transitive cxf inclusions -->
                <!-- none of these are needed for this specific addon -->
                <exclusion>
                    <groupId>org.alfresco</groupId>
                    <artifactId>alfresco-xmlfactory</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.chemistry.opencmis</groupId>
                    <artifactId>chemistry-opencmis-client-impl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.chemistry.opencmis</groupId>
                    <artifactId>chemistry-opencmis-server-bindings</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.cxf</groupId>
                    <artifactId>cxf-rt-rs-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.thedeanda</groupId>
            <artifactId>lorem</artifactId>
            <version>2.2</version>
        </dependency>

        <dependency>
            <groupId>de.acosix.alfresco.utility</groupId>
            <artifactId>de.acosix.alfresco.utility.repo</artifactId>
            <type>amp</type>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>aldica-repo-ignite</artifactId>
            <type>amp</type>
        </dependency>

        <dependency>
            <groupId>org.orderofthebee.support-tools</groupId>
            <artifactId>support-tools-repo</artifactId>
            <classifier>amp</classifier>
            <type>amp</type>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>acs-26</id>
            <properties>
                <alfresco.repo.docker.version>26.1.0</alfresco.repo.docker.version>
                <alfresco.repo.docker.java.version>21</alfresco.repo.docker.java.version>
            </properties>
        </profile>
        <profile>
            <id>acs-25</id>
            <properties>
                <alfresco.repo.docker.version>25.3.0</alfresco.repo.docker.version>
            </properties>
        </profile>
        <profile>
            <id>acs-23</id>
            <properties>
                <alfresco.repo.docker.version>23.3.0</alfresco.repo.docker.version>
            </properties>
        </profile>
    </profiles>
</project>