# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

logger.apache-ignite.name=org.apache.ignite
logger.apache-ignite.level=WARN
logger.apache-ignite-processors.name=org.apache.ignite.internal.processors
logger.apache-ignite-processors.level=WARN
# we want to see topology changes (without them being output only on console)
logger.apache-ignite-discovery.name=org.apache.ignite.internal.managers.discovery.GridDiscoveryManage
logger.apache-ignite-discovery.level=INFO

logger.aldica-common.name=${aldica.ignite-common.basePackage}
logger.aldica-common.level=INFO

logger.aldica-common-discovery.name=${aldica.ignite-common.basePackage}.discovery.CredentialsAwareTcpDiscoverySpi
logger.aldica-common-discovery.level=INFO

logger.aldica-repo.name=${project.basePackage}
logger.aldica-repo.level=INFO