<?xml version="1.0" encoding="UTF-8"?>
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at https://mozilla.org/MPL/2.0/. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.acosix.alfresco.maven</groupId>
        <artifactId>de.acosix.alfresco.maven.project.parent-7.0.0</artifactId>
        <version>1.6.0</version>
    </parent>

    <groupId>org.aldica</groupId>
    <artifactId>aldica-parent</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Alternative/Alfresco Distributed Cache - Parent</name>
    <description>Addon providing distributed caching and data grid capabilities to Alfresco Content Services and Share</description>

    <url>https://github.com/aldica/aldica</url>

    <licenses>
        <license>
            <name>Mozilla Public License, Version 2.0</name>
            <url>https://www.mozilla.org/en-US/MPL/2.0/</url>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git@github.com:aldica/aldica.git</connection>
        <developerConnection>scm:git:git@github.com:aldica/aldica.git</developerConnection>
        <url>git@github.com:aldica/aldica.git</url>
    </scm>

    <developers>
        <developer>
            <id>AFaust</id>
            <name>Axel Faust</name>
            <email>axel.faust@acosix.de</email>
            <organization>Acosix GmbH</organization>
            <roles>
                <role>Founder</role>
                <role>Architect</role>
                <role>Developer</role>
            </roles>
            <properties>
                <twitter>twitter.com/ReluctantBird83</twitter>
            </properties>
        </developer>
        <developer>
            <id>andreaskring</id>
            <name>Andreas Kring</name>
            <email>andreas@magenta.dk</email>
            <organization>Magenta ApS</organization>
            <roles>
                <role>Developer</role>
            </roles>
        </developer>
        <developer>
            <id>skeen</id>
            <name>Emil Madsen</name>
            <email>emil@magenta.dk</email>
            <organization>Magenta ApS</organization>
            <roles>
                <role>Developer</role>
            </roles>
        </developer>
    </developers>

    <properties>
        <messages.path>aldica</messages.path>
        <messages.packageId>aldica</messages.packageId>
        <moduleId>aldica</moduleId>

        <project.longName>Alternative/Alfresco Distributed Cache</project.longName>
        <project.longNameNoWs>AlternativeAlfrescoDistributedCache</project.longNameNoWs>
        <project.basePackage>org.aldica</project.basePackage>

        <maven.shade.version>3.6.0</maven.shade.version>

        <aldica.ignite-common.artifactId>aldica-common-ignite</aldica.ignite-common.artifactId>
        <aldica.ignite-common.basePackage>org.aldica.common.ignite</aldica.ignite-common.basePackage>
        <aldica.ignite-repo.artifactId>aldica-repo-ignite</aldica.ignite-repo.artifactId>

        <acosix.utility.version>1.5.1</acosix.utility.version>
        <ootbee.support-tools.version>1.2.3.1-SNAPSHOT</ootbee.support-tools.version>
        <micrometer.version>1.17.0</micrometer.version>

        <acosix.alfresco.client.version>0.1.0</acosix.alfresco.client.version>
        <!-- making aldica compatible with JDK 17 (e.g. ACS 23.x) requires Ignite 2.14.0 at least -->
        <!-- Ignite 2.17.0+ requires JDK 11, so precludes any ACS version prior to 6.1 -->
        <!-- so we set our minimum to ACS 7.0.0, since ACS 6.x is quite old at this point -->
        <apache.ignite.version>2.18.0</apache.ignite.version>
        <easymock.version>4.2</easymock.version>

        <postgres.docker.version>16</postgres.docker.version>

        <alfresco.activemq.docker.version>5.18-jre17-rockylinux8</alfresco.activemq.docker.version>

        <alfresco.repo.docker.image>alfresco/alfresco-content-repository-community</alfresco.repo.docker.image>
        <alfresco.repo.docker.version>25.2.0</alfresco.repo.docker.version>
        <alfresco.repo.docker.tomcat.path>/usr/local/tomcat</alfresco.repo.docker.tomcat.path>
        <alfresco.repo.docker.amp.path>/usr/local/tomcat/amps</alfresco.repo.docker.amp.path>
        <alfresco.repo.docker.mmt.path>/usr/local/tomcat/alfresco-mmt</alfresco.repo.docker.mmt.path>
        <alfresco.repo.docker.data.path>/usr/local/tomcat/alf_data</alfresco.repo.docker.data.path>
        <alfresco.repo.docker.port>8180</alfresco.repo.docker.port>
        <alfresco.repo.docker.debugPort>8185</alfresco.repo.docker.debugPort>
        <alfresco.repo.docker.commPort>47100</alfresco.repo.docker.commPort>
        <alfresco.repo.docker.discoPort>47110</alfresco.repo.docker.discoPort>
        <alfresco.repo.docker.timePort>47120</alfresco.repo.docker.timePort>
        <alfresco.repo.docker.port2>8280</alfresco.repo.docker.port2>
        <alfresco.repo.docker.debugPort2>8285</alfresco.repo.docker.debugPort2>
        <alfresco.repo.docker.commPort2>47102</alfresco.repo.docker.commPort2>
        <alfresco.repo.docker.discoPort2>47112</alfresco.repo.docker.discoPort2>
        <alfresco.repo.docker.timePort2>47122</alfresco.repo.docker.timePort2>
        <alfresco.repo.docker.build.preRun>USER root</alfresco.repo.docker.build.preRun>
        <alfresco.repo.docker.build.postRun>USER alfresco</alfresco.repo.docker.build.postRun>
        <alfresco.repo.docker.chown.mask>alfresco:Alfresco</alfresco.repo.docker.chown.mask>

        <alfresco.share.docker.image>alfresco/alfresco-share</alfresco.share.docker.image>
        <alfresco.share.docker.version>25.2.0</alfresco.share.docker.version>
        <alfresco.share.docker.tomcat.path>/usr/local/tomcat</alfresco.share.docker.tomcat.path>
        <alfresco.share.docker.amp.path>/usr/local/tomcat/share_amps</alfresco.share.docker.amp.path>
        <alfresco.share.docker.mmt.path>/usr/local/tomcat/alfresco-mmt</alfresco.share.docker.mmt.path>
        <alfresco.share.docker.port>8181</alfresco.share.docker.port>
        <alfresco.share.docker.debugPort>8186</alfresco.share.docker.debugPort>
        <alfresco.share.docker.port2>8281</alfresco.share.docker.port2>
        <alfresco.share.docker.debugPort2>8286</alfresco.share.docker.debugPort2>
        
        <aldica.companion.docker.image>openjdk</aldica.companion.docker.image>
        <aldica.companion.docker.version>11.0.11-jdk-slim</aldica.companion.docker.version>
        <aldica.companion.docker.debugPort>8190</aldica.companion.docker.debugPort>
        <aldica.companion.docker.debugPort2>8290</aldica.companion.docker.debugPort2>

        <alfresco.aio.docker.version>5.1.5</alfresco.aio.docker.version>
        <alfresco.solr6.docker.version>2.0.12</alfresco.solr6.docker.version>
    </properties>

    <repositories>
        <repository>
            <id>central-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>central-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <repository>
            <id>central</id>
            <url>https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/</url>
        </repository>
        <snapshotRepository>
            <id>central</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.ignite</groupId>
                <artifactId>ignite-core</artifactId>
                <version>${apache.ignite.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.gridgain</groupId>
                        <artifactId>ignite-shmem</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>org.apache.ignite</groupId>
                <artifactId>ignite-slf4j</artifactId>
                <version>${apache.ignite.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>de.acosix.alfresco.utility</groupId>
                <artifactId>de.acosix.alfresco.utility.common</artifactId>
                <version>${acosix.utility.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>de.acosix.alfresco.utility</groupId>
                <artifactId>de.acosix.alfresco.utility.core.repo</artifactId>
                <version>${acosix.utility.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>de.acosix.alfresco.utility</groupId>
                <artifactId>de.acosix.alfresco.utility.core.share</artifactId>
                <version>${acosix.utility.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-core</artifactId>
                <version>${micrometer.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>

                <plugin>
                    <groupId>de.thetaphi</groupId>
                    <artifactId>forbiddenapis</artifactId>
                    <configuration>
                        <failOnUnsupportedJava>false</failOnUnsupportedJava>
                        <failOnMissingClasses>false</failOnMissingClasses>
                        <failOnUnresolvableSignatures>false</failOnUnresolvableSignatures>
                        <bundledSignatures>
                            <bundledSignature>jdk-unsafe</bundledSignature>
                            <bundledSignature>jdk-deprecated</bundledSignature>
                            <bundledSignature>jdk-internal</bundledSignature>
                            <bundledSignature>jdk-system-out</bundledSignature>
                            <bundledSignature>jdk-non-portable</bundledSignature>
                            <!-- disabled (compared to inherited default) as we can't avoid setAccessible -->
                            <!-- 
                            <bundledSignature>jdk-reflection</bundledSignature>
                             -->
                        </bundledSignatures>
                    </configuration>
                </plugin>

                <plugin>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${maven.shade.version}</version>
                </plugin>

                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <argLine><![CDATA[
                            -Xmx512M
                            -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication
                            -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
                            --add-opens=java.base/java.io=ALL-UNNAMED
                            --add-opens=java.base/java.lang=ALL-UNNAMED
                            --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
                            --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
                            --add-opens=java.base/java.math=ALL-UNNAMED
                            --add-opens=java.base/java.net=ALL-UNNAMED
                            --add-opens=java.base/java.nio=ALL-UNNAMED
                            --add-opens=java.base/java.text=ALL-UNNAMED
                            --add-opens=java.base/java.time=ALL-UNNAMED
                            --add-opens=java.base/java.util=ALL-UNNAMED
                            --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
                            --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
                            --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
                            --add-opens=java.base/javax.crypto=ALL-UNNAMED
                            --add-opens=java.base/jdk.internal.access=ALL-UNNAMED
                            --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
                            --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
                            --add-opens=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED
                            --add-opens=java.base/sun.util.calendar=ALL-UNNAMED
                            --add-opens=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
                            --add-opens=java.management/sun.management=ALL-UNNAMED
                            --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
                            --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
                            --illegal-access=permit
                            -Dfile.encoding=UTF-8
                            -Djava.net.preferIPv4Stack=true
                            -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true
                            -DIGNITE_QUIET=true
                            -DIGNITE_NO_ASCII=true
                            -DIGNITE_UPDATE_NOTIFIER=false
                            -DIGNITE_JVM_PAUSE_DETECTOR_DISABLED=true
                        ]]></argLine>
                    </configuration>
                </plugin>

                <plugin>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <configuration>
                        <argLine><![CDATA[
                            -Xmx512M
                            -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication
                            -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
                            --add-opens=java.base/java.io=ALL-UNNAMED
                            --add-opens=java.base/java.lang=ALL-UNNAMED
                            --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
                            --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
                            --add-opens=java.base/java.math=ALL-UNNAMED
                            --add-opens=java.base/java.net=ALL-UNNAMED
                            --add-opens=java.base/java.nio=ALL-UNNAMED
                            --add-opens=java.base/java.text=ALL-UNNAMED
                            --add-opens=java.base/java.time=ALL-UNNAMED
                            --add-opens=java.base/java.util=ALL-UNNAMED
                            --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
                            --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
                            --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
                            --add-opens=java.base/javax.crypto=ALL-UNNAMED
                            --add-opens=java.base/jdk.internal.access=ALL-UNNAMED
                            --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
                            --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
                            --add-opens=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED
                            --add-opens=java.base/sun.util.calendar=ALL-UNNAMED
                            --add-opens=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
                            --add-opens=java.management/sun.management=ALL-UNNAMED
                            --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
                            --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
                            --illegal-access=permit
                            -Dfile.encoding=UTF-8
                            -Djava.net.preferIPv4Stack=true
                            -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true
                            -DIGNITE_QUIET=true
                            -DIGNITE_NO_ASCII=true
                            -DIGNITE_UPDATE_NOTIFIER=false
                            -DIGNITE_JVM_PAUSE_DETECTOR_DISABLED=true
                        ]]></argLine>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <modules>
        <module>common</module>
        <module>repository</module>
        <module>repository-companion</module>
        <module>share</module>
    </modules>
    
    <profiles>
        <profile>
            <id>surefireSuppression</id>

            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <artifactId>maven-surefire-plugin</artifactId>
                            <configuration>
                                <skipTests>true</skipTests>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>

        <profile>
            <id>dockerTest</id>

            <modules>
                <module>docker-test</module>
            </modules>
        </profile>
    </profiles>
</project>
