# Download AMPs
FROM maven:3-jdk-11

RUN mvn dependency:copy -Dartifact=de.acosix.alfresco.utility:de.acosix.alfresco.utility.core.share:1.2.2:amp -DoutputDirectory=/tmp -B
RUN mvn dependency:copy -Dartifact=org.aldica:aldica-share-ignite:1.0.0:amp -DoutputDirectory=/tmp -B

# Build aldica-enabled Alfresco Share
FROM alfresco/alfresco-share:6.2.0

COPY --from=0 /tmp/aldica-share-ignite-1.0.0-SNAPSHOT.amp .
COPY --from=0 /tmp/de.acosix.alfresco.utility.core.share-1.2.2.amp .

RUN java -jar alfresco-mmt/alfresco-mmt-6.0.jar install de.acosix.alfresco.utility.core.share-1.2.2.amp webapps/share -force -nobackup
RUN java -jar alfresco-mmt/alfresco-mmt-6.0.jar install aldica-share-ignite-1.0.0.amp webapps/share -nobackup
