<?xml version="1.0" encoding="UTF-8"?>
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at https://mozilla.org/MPL/2.0/. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.aldica</groupId>
        <artifactId>aldica-parent</artifactId>
        <version>1.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>aldica-share-ignite</artifactId>
    <name>Alternative/Alfresco Distributed Cache - Share Ignite Module</name>
    <description>Share-tier addon to provide Ignite-based distributed caching and data grid capabilities</description>

    <properties>
        <project.basePackage>org.aldica.share.ignite</project.basePackage>
        <docker.tests.versionSpecificJavaOpts></docker.tests.versionSpecificJavaOpts>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${surf.groupId}</groupId>
                <artifactId>spring-surf</artifactId>
                <version>${surf.share.api.version}</version>
            </dependency>

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>${aldica.ignite-common.artifactId}</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>${aldica.ignite-common.artifactId}</artifactId>
        </dependency>

        <dependency>
            <groupId>de.acosix.alfresco.utility</groupId>
            <artifactId>de.acosix.alfresco.utility.core.share</artifactId>
        </dependency>

        <dependency>
            <groupId>org.alfresco</groupId>
            <artifactId>share</artifactId>
            <classifier>classes</classifier>
        </dependency>

        <dependency>
            <groupId>${surf.groupId}</groupId>
            <artifactId>spring-surf</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>yuicompressor-maven-plugin</artifactId>
            </plugin>
        </plugins>

    </build>

</project>